name: Setup Terminus

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Installing PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: '7.4'
    - name: Installing Terminus
      uses: kopepasah/setup-pantheon-terminus@master
      with:
        pantheon-machine-token: ${{ secrets.PANTHEON_MACHINE_TOKEN }}
    - name: Listing Sites
      if: success()
      run: terminus site:list

  # terminus connection:set my-site.dev sftp
  # terminus env:deploy my-site.test --sync-content --note="Deploy core and contrib updates"
  # terminus env:clear-cache <site>.test
  # terminus multidev:create  -- rstudio.development <multidev>

